### ISSUE TITLE
生成computer.secl文件时报错

### ISSUE THREAD

**Issue by Izimi** [metowolf/rime-sogou#1]
安装 ```npm i rime-sogou -g```
当我使用```rime-sogou ./dictionaries/computer.scel```，报错如下
![image](https://user-images.githubusercontent.com/34852697/90209757-c7c23480-de1e-11ea-9470-192ac606f729.png)
我的理解是路径文件不存在，但是不是应该是生成文件么？
烦请大大看看是什么问题

**Comment by metowolf** [comment]
这里应该是找不到 d:\computer.scel 文件，也就是你下载的搜狗细胞词库文件

**Comment by Izimi** [comment]
请问搜狗细胞词库文件在哪里获取呢？

**Comment by metowolf** [comment]
https://pinyin.sogou.com/dict/

**Comment by Izimi** [comment]
会错意了，抱歉！
已正常运行，非常感谢！
